routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/user', function () {
    \Illuminate\Support\Facades\Auth::LoginUsingId(2);
});

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', function () {
    return redirect()->route('admin.home');
});

Route::get('/app', function () {
    return view('layouts.spa');
});

Route::group(['prefix' => '/', 'as' => 'site.'], function () {
    Route::get('/', function(){
        return view('site.home');
    })->name('home');

    Route::group(['prefix' => 'subscriptions','as' => 'subscriptions.','middleware'=>'auth'], function(){
        Route::get('create','Site\SubscriptionsController@create')->name('create');
        Route::post('store','Site\SubscriptionsController@store')->name('store');
        Route::get('successfully','Site\SubscriptionsController@successfully')->name('successfully');
    });

    Route::group(['prefix'=>'my-financial','as'=>'my_financial','middleware'=>'auth.from_token'],function(){
       Route::get('/', function(){
           echo 'teste';
       });
    });

    Route::get('register','Site\Auth\RegisterController@create')->name('auth.register.create');
    Route::post('register','Site\Auth\RegisterController@store')->name('auth.register.store');

    Route::get('login','Site\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Site\Auth\LoginController@login');
    Route::post('logout','Site\Auth\LoginController@logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Auth::routes();
    Route::group(['middleware' => 'can:access-admin'], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('banks', 'Admin\BanksController', ['except' => 'show']);
    });
});

app/Models/Subscription.php
<?php

namespace CodeFin\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Subscription extends Model implements Transformable
{
    use TransformableTrait;

    const STATUS_ATIVE = 1;
    const STATUS_INATIVE = 2;

    protected $fillable = [
        'expires_at',
        'canceled_at',
        'code',
        'user_id',
        'plan_id',
        'status',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/Site/SubscriptionsController.php
<?php

namespace CodeFin\Http\Controllers\Site;

use CodeFin\Http\Controllers\Controller;
use CodeFin\Http\Requests\SubscriptionCreateRequest;
use CodeFin\Iugu\Exceptions\AbstractIuguException;
use CodeFin\Iugu\Exceptions\IuguCustomerException;
use CodeFin\Iugu\Exceptions\IuguPaymentMethodException;
use CodeFin\Iugu\Exceptions\IuguSubscriptionException;
use CodeFin\Iugu\IuguSubscriptionManager;
use CodeFin\Repositories\Interfaces\PlanRepository;
use Illuminate\Support\Facades\Auth;

class SubscriptionsController extends Controller
{
    /**
     * @var PlanRepository
     */
    private $planRepository;
    /**
     * @var IuguSubscriptionManager
     */
    private $iuguSubscriptionManager;

    public function __construct(PlanRepository $planRepository, IuguSubscriptionManager $iuguSubscriptionManager)
    {
        $this->planRepository = $planRepository;
        $this->iuguSubscriptionManager = $iuguSubscriptionManager;
    }

    public function create()
    {
        $plan = $this->planRepository->all()->first();
        return view('site.subscriptions.create', compact('plan'));
    }

    public function store(SubscriptionCreateRequest $request)
    {
        $plan = $this->planRepository->all()->first();

        try {
            $this->iuguSubscriptionManager->create(
                Auth::user(), $plan, $request->all()
            );
        } catch (AbstractIuguException $e) {
            //dd($e);
            $request->session()->flash('error',$this->getMessageException($e));
            return redirect()->route('site.subscriptions.create');
        }

        return redirect()->route('site.subscriptions.successfully');
    }

    public function successfully()
    {
        return view('site.subscriptions.successfully');
    }

    protected function getMessageException($exception)
    {
        if ($exception instanceof IuguCustomerException) {
            //return $exception->getErrors();
            return 'Erro ao processar cliente. Contacte o atendimento para mais detalhes.';
        } elseif ($exception instanceof IuguPaymentMethodException) {
            return 'Erro ao salvar método de pagamento. Contacte o atendimento para mais detalhes.';
        }elseif ($exception instanceof IuguSubscriptionException) {
            return 'Erro ao processar assinatura. Contacte o atendimento para mais detalhes.';
        }
    }
}

resources/views/site/subscriptions/create.blade.php
@extends('layouts.site')

@section('content')
    <div class="container">
        @if(Session::has('error'))
            <div class="row">
                <div class="col s12">
                    <div class="card-panel red">
                        <span class="white-text">{{Session::get('error')}}</span>
                    </div>
                </div>
            </div>
        @endif
        <div class="row">
            <subscription-create
                :plan="{{json_encode($plan->toArray())}}"
                csrf_token="{{csrf_token()}}"
                action="{{route('site.subscriptions.store')}}">
            </subscription-create>
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript" src="https://js.iugu.com/v2"></script>
@endpush

resources/views/site/subscriptions/successfully.blade.php
@extends('layouts.site')

@section('content')
    <div class="container">
        <div class="row">
            <div class="card-panel center">
                <span class="blue-grey-text text-darken-2">
                    <h2>Parabéns, sua assinatura foi criada!</h2>
                    <p>Quando o pagamento for autorizado, você receberá as informações de acesso no e-mail cadastrado.</p>
                </span>
            </div>
        </div>
    </div>
@endsection