routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/user', function () {
    \Illuminate\Support\Facades\Auth::LoginUsingId(2);
});

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', function () {
    return redirect()->route('admin.home');
});

Route::get('/app', function () {
    return view('layouts.spa');
});

Route::group(['prefix' => '/', 'as' => 'site.'], function () {
    Route::get('/', function(){
        return view('site.home');
    })->name('home');

    Route::group(['prefix' => 'subscriptions','as' => 'subscriptions.','middleware'=>'auth'], function(){
        Route::get('create','Site\SubscriptionsController@create')->name('create');
        Route::post('store','Site\SubscriptionsController@store')->name('store');
        Route::get('successfully','Site\SubscriptionsController@successfully')->name('successfully');
    });

    Route::group(['prefix'=>'my-financial','as'=>'my_financial','middleware'=>'auth.from_token'],function(){
       Route::get('/', function(){
           echo 'teste';
       });
    });

    Route::get('register','Site\Auth\RegisterController@create')->name('auth.register.create');
    Route::post('register','Site\Auth\RegisterController@store')->name('auth.register.store');

    Route::get('login','Site\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Site\Auth\LoginController@login');
    Route::post('logout','Site\Auth\LoginController@logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Auth::routes();
    Route::group(['middleware' => 'can:access-admin'], function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('banks', 'Admin\BanksController', ['except' => 'show']);
    });
});

app/Models/Bank.php
<?php

namespace CodeFin\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Bank extends Model implements Transformable
{
    use TransformableTrait;

    const LOGOS_DIR = "banks/images";

    protected $fillable = [
        'name',
        'logo'
    ];

    public function getLogosDirAttribute()
    {
        return self::LOGOS_DIR;
    }

    public function getLogoPathAttribute()
    {
        $folder = $this->getLogosDirAttribute();
        $logo = $this->attributes['logo'];
        return "storage/$folder/$logo";
    }

}

app/Http/Controllers/Admin/BanksController.php
<?php

namespace CodeFin\Http\Controllers\Admin;

use CodeFin\Events\BankCreatedEvent;
use CodeFin\Http\Controllers\Controller;
use CodeFin\Http\Controllers\Response;
use CodeFin\Http\Requests;
use CodeFin\Http\Requests\BankCreateRequest;
use CodeFin\Http\Requests\BankUpdateRequest;
use CodeFin\Models\Bank;
use CodeFin\Repositories\Interfaces\BankRepository;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;


class BanksController extends Controller
{

    /**
     * @var BankRepository
     */
    protected $repository;


    public function __construct(BankRepository $repository)
    {
        $this->repository = $repository;
        $this->repository->skipPresenter(true);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = $this->repository->paginate(3);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $banks,
            ]);
        }

        return view('admin.banks.index', compact('banks'));
    }

    public function create()
    {
        return view('admin.banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  BankCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(BankCreateRequest $request)
    {
        $data = $request->all();
        $bank = $this->repository->create($data);

        if ($request->wantsJson()) {
            $response = [
                'message' => 'Bank created.',
                'data' => $bank->toArray(),
            ];

            return response()->json($response);
        }

        return redirect()->route('admin.banks.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $bank = $this->repository->find($id);

        return view('admin.banks.edit', compact('bank'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  BankUpdateRequest $request
     * @param  string $id
     *
     * @return Response
     */
    public function update(BankUpdateRequest $request, $id)
    {
        $bank = $this->repository->update($request->all(), $id);


        if ($request->wantsJson()) {
            $response = [
                'message' => 'Bank updated.',
                'data' => $bank->toArray(),
            ];
            return response()->json($response);
        }

        return redirect()->route('admin.banks.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {
            return response()->json([
                'message' => 'Bank deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->route('admin.banks.index');
    }
}

app/Http/Controllers/Api/BanksController.php
<?php

namespace CodeFin\Http\Controllers\Api;

use CodeFin\Http\Controllers\Controller;
use CodeFin\Http\Controllers\Response;
use CodeFin\Http\Requests;
use CodeFin\Http\Requests\BankAccountCreateRequest;
use CodeFin\Http\Requests\BankAccountUpdateRequest;
use CodeFin\Repositories\Interfaces\BankAccountRepository;
use CodeFin\Repositories\Interfaces\BankRepository;


class BanksController extends Controller
{
    /**
     * @var BankRepository
     */
    protected $repository;


    public function __construct(BankRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        return $this->repository->all();
    }
}

resources/views/admin/banks/_form.blade.php
@include('errors._error_field')
<?php  $errorClass = $errors->first('name') ? ['class'=>'validate invalid'] : []; ?>
<div class="row">
    <div class="input-field">
        {!! Form::text('name', null, $errorClass) !!}
        {!! Form::label('name','Nome',['data-error' => $errors->first('name')]) !!}
    </div>
    <div class="input-field file-field">
        <div class="btn">
            <span>Logo</span>
            {!! Form::file('logo') !!}
        </div>
        <div class="file-path-wrapper">
            <input type="text" class="file-path"/>
        </div>
    </div>
</div>

resources/views/admin/banks/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <h4>Novo Banco</h4>
            {!! Form::open(['route'=>'admin.banks.store','files'=>true]) !!}
            @include('admin.banks._form')
            <div class="row">
                    {!! Form::submit('Criar banco',['class'=>'btn waves-effect right']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/banks/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <h4>Editar Banco</h4>
            {!! Form::model($bank,['route'=>['admin.banks.update','bank'=>$bank->id],'method'=>'PUT','files'=>true]) !!}
            @include('admin.banks._form')
            <div class="row">
                {!! Form::submit('Salvar banco',['class'=>'btn waves-effect']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/banks/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <h4>Listagem de bancos</h4>
            <a href="{{route('admin.banks.create')}}" class="btn waves-effect">Novo banco</a>

            <table class="striped responsive-table centered highline responsive-table z-depth-5">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>
                @foreach($banks as $item)
                    <tr>
                        <td>
                            <div class="row valign-wrapper">
                                <div class="col s12">{{$item->id}}</div>
                            </div>
                        </td>
                        <td>
                            <div class="row valign-wrapper">
                                <div class="col s2">
                                    <img src="{{asset($item->logo_path)}}" class="bank-logo">
                                </div>
                                <div class="col s10">
                                    <span class="left">{{$item->name}}</span>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="row valign-wrapper">
                                <div class="col s12">
                                    <a href="{{route('admin.banks.edit',['bank'=>$item->id])}}">Editar</a>
                                    <delete-action action="{{route('admin.banks.destroy',['bank'=>$item->id])}}"
                                                   action-element="link-delete-{{$item->id}}"
                                                   csrf-token="{{csrf_token()}}">
                                        <?php
                                        $modalId = "modal-delete-$item->id";
                                        $deleteRoute = route('admin.banks.destroy', ['bank' => $item->id]);
                                        ?>
                                        <a id="link-modal-{{$item->id}}" href="#{{$modalId}}">Excluir</a>
                                        <modal :modal="{{json_encode(['id'=>$modalId])}}" style="display: none">
                                            <div slot="content">
                                                <h5>Mensagem de confirmação</h5>
                                                <p><strong>Deseja excluir esse banco?</strong></p>
                                                <div class="divider"></div>
                                                <p>Nome: <strong>{{$item->name}}</strong></p>
                                                <div class="divider"></div>
                                            </div>
                                            <div slot="footer">
                                                <button id="link-delete-{{$item->id}}"
                                                        class="btn btn-flat waves-effect green lighten-2 modal-close modal-action">
                                                    Ok
                                                </button>
                                                <button class="btn btn-flat waves-effect waves-red modal-close modal-action">
                                                    Cancelar
                                                </button>
                                            </div>
                                        </modal>
                                    </delete-action>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {!! $banks->links() !!}
        </div>
    </div>
@endsection